# Generated by Django 5.2.1 on 2026-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_final_outcome_report_selected_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='analysis_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
