# Generated by Django 5.2.1 on 2026-03-24 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_analysis_end_date'),
    ]

    operations = []
