# Generated by Django 5.2.1 on 2026-04-18 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_report_updated_by(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    for report in Report.objects.filter(updated_by__isnull=True):
        report.updated_by_id = report.manager_id or report.created_by_id
        report.save(update_fields=["updated_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttemplate_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_report_updated_by, migrations.RunPython.noop),
    ]
