# Generated by Django 5.2.1 on 2026-03-02 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('client_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('sample_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_no', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=100)),
                ('priority', models.CharField(default='Normal', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
