# Generated by Django 5.2.1 on 2026-03-03 05:59

import django.db.models.deletion
from django.db import migrations, models


def migrate_sample_name_to_master(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    SampleNameMaster = apps.get_model('bookings', 'SampleNameMaster')

    legacy_names = {
        name.strip()
        for name in Booking.objects.exclude(sample_name_legacy__isnull=True).values_list('sample_name_legacy', flat=True)
        if (name or '').strip()
    }
    if not legacy_names:
        return

    existing = set(SampleNameMaster.objects.filter(name__in=legacy_names).values_list('name', flat=True))
    to_create = [SampleNameMaster(name=name) for name in legacy_names if name not in existing]
    if to_create:
        SampleNameMaster.objects.bulk_create(to_create, ignore_conflicts=True, batch_size=1000)

    master_map = dict(SampleNameMaster.objects.filter(name__in=legacy_names).values_list('name', 'id'))
    for legacy_name, master_id in master_map.items():
        Booking.objects.filter(sample_name_legacy=legacy_name).update(sample_name_id=master_id)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufacturerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocolMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleNameMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmitterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UOMMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sample_name',
            new_name='sample_name_legacy',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='test_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('regulatory', 'Regulatory'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='sample_reg_no',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('API', 'API'), ('FG', 'FG'), ('Food', 'Food'), ('RM', 'RM'), ('Stability', 'Stability')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.customermaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.manufacturermaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.protocolmaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sample_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.samplenamemaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.submittermaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='test_to_be_performed',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.testmaster'),
        ),
        migrations.AddField(
            model_name='booking',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.uommaster'),
        ),
        migrations.RunPython(migrate_sample_name_to_master, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='booking',
            name='sample_name_legacy',
        ),
    ]
