# Generated by Django 5.2.1 on 2026-04-18 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_booking_updated_by(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.filter(updated_by__isnull=True):
        booking.updated_by_id = booking.approved_by_id or booking.created_by_id
        booking.save(update_fields=["updated_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_customermaster_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_booking_updated_by, migrations.RunPython.noop),
    ]
