# Generated by Django 5.2.1 on 2026-04-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_updated_at_booking_updated_by'),
        ('reports', '0008_report_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmaster',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tests', to='reports.reporttemplate'),
        ),
    ]
