# Generated by Django 5.2.1 on 2026-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_testmaster_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_sr_no',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
